# Generated by Django 3.2.5 on 2021-07-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_height', models.IntegerField(verbose_name='Высота блока')),
                ('block_hash', models.TextField(verbose_name='Хэш блока')),
                ('block_time', models.IntegerField(default=None, verbose_name='Время блока')),
                ('block_address', models.TextField(max_length=60, verbose_name='Адрес майнера')),
                ('block_numbers', models.IntegerField(verbose_name='Кол-во транзакций')),
            ],
            options={
                'verbose_name': 'Адрес майнера',
                'verbose_name_plural': 'Адреса майнеров',
            },
        ),
    ]
