# Generated by Django 3.2.5 on 2021-07-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCSchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infblock',
            name='block_time',
            field=models.IntegerField(verbose_name='Время блока'),
        ),
    ]
