# Generated by Django 3.2.5 on 2021-07-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BCSchain', '0002_alter_infblock_block_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infblock',
            old_name='block_time',
            new_name='timestamp',
        ),
    ]
