# Generated by Django 3.2.5 on 2021-07-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCSchain', '0003_rename_block_time_infblock_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infblock',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='infblock',
            name='block_time',
            field=models.IntegerField(default=None, verbose_name='Время блока'),
        ),
    ]
