# Generated by Django 3.2.5 on 2021-07-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BCSchain', '0005_auto_20210719_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infblock',
            name='timestamp',
        ),
    ]
