# Generated by Django 3.2.5 on 2021-07-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCSchain', '0006_remove_infblock_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infblock',
            name='block_time',
            field=models.IntegerField(default=None, verbose_name='Время старта блока'),
        ),
    ]
